### ISSUE TITLE
Перевод через гугль не работает

### ISSUE THREAD

**Issue by Gexon** [SnakeSel/PotBS_LangUI#1]
Жму синюю кнопку с изображением гугль-переводчика, но перевод не появляется, вместо него английский текст(в правой части окна).
Если удалить все слова в правой части и нажать кнопку гугль-перевода, то он снова подставляет туда английский текст, точно такой же как в левой части окна.

**Comment by SnakeSel** [comment]
Здравствуйте.
Вы ведь используете программу для перевода другой игры?
Понял причину, у меня язык перевода с\на который переводить выбирается по первым 2 символам из имени файла перевода. Скорее всего у Вас в игре файлы имеют отличное название.
Добавлю возможность задать язык перевода в файле настроек. 
Пока, как временное решение, переименуйте файлы перевода, написав в начале "en"(если переводите с английского) в имени исходного файла и "ru" в имени файла перевода.

**Comment by Gexon** [comment]
Я перевожу файлы из игры EverQuest2,
Да, действительно, у меня оба файла были как "en_us_dict.dat" но в разных папках =)

**Comment by Gexon** [comment]
После того как в названии файла добавил "ru" - переводчик заработал! Спасибо)
