### ISSUE TITLE
Закрывается после выбора файлов перевода, PotBS_LangUI_Win64_20210904

### ISSUE THREAD

**Issue by Gexon** [SnakeSel/PotBS_LangUI#4]
PotBS_LangUI_Win64_20210904 - эта версия не работает.
1. Запускаю с файла potbs_langui.exe
2. Выходит окно "Выберите источник перевода"
3. Указываю файл en_us_data.dat - это файл от Everquest2
4. Выходит окно "Укажите файл назначения перевода"
5. Указываю на en_us_data.dat
6. Всё) Программа пропадает из диспетчера. Логов не нашел)

**Comment by Gexon** [comment]
PotBS_LangUI_Win64_20210425 - эта версия тоже не запускается.
PotBS_LangUI_Win64_20200605 - эта работает. Может эта специально для Everquest2?)

**Comment by Gexon** [comment]
Могу ли я добавлять новые строки в оригинальный файл, а затем их переводить на русский?
Дело в том что файл en_us_data.dat от 2015года), а в игре появились новые тексты в интерфейсе которых нет в старом переводе.

**Comment by SnakeSel** [comment]
Ох, как давно это было)
Для появления лога откройте конфиг программы (data/cfg.ini) и пропишите:
```
[Main]
Log  = potbs_langui.log
```

**Comment by SnakeSel** [comment]
По умолчанию программа пытается определить язык перевода через онлайн сервис.
Возможно в этом и ошибка сейчас.
откройте конфиг программы (data/cfg.ini) и пропишите:
```
[Project]
# Доступные значения: "AUTO","FILE","RU", "EN", "FR", "DE", "ES"
SourceLang=FILE
TargetLang=FILE
```
или напрямую укажите:
```
[Project]
SourceLang=EN
TargetLang=RU
```

**Comment by SnakeSel** [comment]
> Могу ли я добавлять новые строки в оригинальный файл, а затем их переводить на русский?

Через программу добавить новые строки не получится (я это так и не реализовал). Если добавите сами в любом текстовом редакторе в оригиналный .dat, то программа их увидит и можно будет перевести.

**Comment by Gexon** [comment]
> Ох, как давно это было) Для появления лога откройте конфиг программы (data/cfg.ini) и пропишите:
> 
> ```
> [Main]
> Log  = potbs_langui.log
> ```

логи включил.
файла cfg.ini не было, был с другим именем, переименовал его и раскомментировал нужную строку.

**Comment by Gexon** [comment]
> По умолчанию программа пытается определить язык перевода через онлайн сервис. Возможно в этом и ошибка сейчас. откройте конфиг программы (data/cfg.ini) и пропишите:
> 
> ```
> [Project]
> # Доступные значения: "AUTO","FILE","RU", "EN", "FR", "DE", "ES"
> SourceLang=FILE
> TargetLang=FILE
> ```
> 
> или напрямую укажите:
> 
> ```
> [Project]
> SourceLang=EN
> TargetLang=RU
> ```

не помогло, пишет следующее:
```
2024/04/24 12:56:33 Запуск PotBS_LangUI, версия: 20210904
2024/04/24 12:56:41 [ERR]	Ошибка загрузки файлов
```

**Comment by SnakeSel** [comment]
> не помогло

Можете файл выложить? Гляну что там не так

**Comment by Gexon** [comment]
https://disk.yandex.ru/d/gvPU4rw2K1nkog - англ 
https://disk.yandex.ru/d/pQC_2ic-0vhUeQ - рус
прикрепить не смог, больше 40мб не принимает сюда

**Comment by SnakeSel** [comment]
Хм, en_us_data.dat это оригинал из игры? Почему-то заголовок другой в файле. Можно еще от него .dir
Собственно поэтому и вылет:
```
2024/04/24 11:29:32 Запуск PotBS_LangUI, версия: 20230617
2024/04/24 11:29:37 [ERR]	Error Load file /home/mks/opt/PotBS_LangUI/test/en_us_data.dat. The file does not start with ï»¿
```
А в руссском в первой строке нет id строки (598).

**Comment by Gexon** [comment]
> Хм, en_us_data.dat это оригинал из игры? Почему-то заголовок другой в файле. Можно еще от него .dir А в руссском в первой строке нет id строки (598).

да, с игры, не изменял его.
PotBS_LangUI_Win64_20200605 - эта версия открывает нормально. Может им пользоваться?)
Но он не экспортирует в Exel формат, при попытке экспорта - закрывается.
[Uploading en_us_data.zip…]()

**Comment by SnakeSel** [comment]
> Uploading en_us_data.zip…

Ссылка ведет на этот issues. Нет файла

**Comment by SnakeSel** [comment]
Поправил заголовок, теперь откроется
https://drive.google.com/file/d/1wr7Zf_-A4YHy91GhG26GWDBywQ80-LGl/view?usp=sharing

Вообще надо допилить открывание по .dir при его наличии

**Comment by Gexon** [comment]
Да, теперь нормально открывается, спасибо!
Проблема была в файле en_us_data.dat
